### ISSUE TITLE
Fonction rf :

### ISSUE THREAD

**Issue by TitouanRobert** [anaislaot/optiMod#1]
Bonjour,

Pour le moment, le calcul du modèle et le calcul du critère d'optim ce font dans la même boucle. Je pense qu'il faudrait faire 2 boucles : 

La première fait les modèles et donne en sortie les Y&Ypredit + proba (ce que sort actuellement de la fonction .predRF). En sortie nous avons donc une liste de ces objets.

La deuxième boucle calcul pour chacun de ces objets le critère d'optimisation.

Une fois ces 2 boucles faites je pense qu'il faut une fonction qui prend en entrée un vecteur composé du critère d'optimisation calculé pour chaque modèle de la grille, des listes  Y&Ypredit + proba fournie par .predRF et du type de critère à optimisé (AUC, RMSE...). Cette fonction aurait en sortie la liste Y-Ypredit + proba qui minimise l'erreur + les 2-3 stats qui nous intéresses.

**Comment by anaislaot** [comment]
C'est réglé.
